#!/bin/bash
# Moodle Komodo Quick Reference
# Common commands for managing Moodle stack in Komodo

echo "Moodle Komodo Stack - Quick Reference"
echo "===================================="
echo ""

# Stack Directory
STACK_DIR="/etc/komodo/stacks/moodle"

# ==================== DEPLOYMENT ====================
echo "DEPLOYMENT:"
echo "-----------"
echo "Build Docker image:"
echo "  docker build -f $STACK_DIR/moodle.Dockerfile -t moodle:latest /etc/komodo/repos/moodle"
echo ""
echo "Deploy stack (docker-compose):"
echo "  cd $STACK_DIR && docker-compose up -d"
echo ""
echo "Deploy via Komodo API (after configuring register-moodle.py):"
echo "  python3 /root/komodo/register-moodle.py"
echo ""

# ==================== MONITORING ====================
echo "MONITORING:"
echo "-----------"
echo "Check stack status:"
echo "  docker-compose -f $STACK_DIR/docker-compose.yml ps"
echo ""
echo "View Moodle logs (live):"
echo "  docker logs -f moodle"
echo ""
echo "View database logs (live):"
echo "  docker logs -f moodle-db"
echo ""
echo "Check container health:"
echo "  docker inspect moodle | grep -A 5 '\"Health\"'"
echo ""

# ==================== DATABASE ====================
echo "DATABASE:"
echo "---------"
echo "Connect to database CLI:"
echo "  docker exec -it moodle-db psql -U moodle -d moodle"
echo ""
echo "Test database connection:"
echo "  docker exec moodle psql -h moodle-db -U moodle -d moodle -c 'SELECT 1;'"
echo ""
echo "Backup database:"
echo "  docker exec moodle-db pg_dump -U moodle -d moodle > /root/komodo/backups/moodle_\$(date +%Y%m%d_%H%M%S).sql"
echo ""
echo "Restore database:"
echo "  docker exec -i moodle-db psql -U moodle -d moodle < /path/to/backup.sql"
echo ""

# ==================== FILES & CONFIGURATION ====================
echo "FILES & CONFIGURATION:"
echo "---------------------"
echo "Edit environment variables:"
echo "  nano $STACK_DIR/.env"
echo ""
echo "Edit Moodle config:"
echo "  nano $STACK_DIR/config.php"
echo ""
echo "View moodledata directory:"
echo "  docker exec moodle ls -la /var/www/moodledata"
echo ""
echo "Check disk usage:"
echo "  du -sh /var/www/moodledata"
echo ""

# ==================== CONTAINER MANAGEMENT ====================
echo "CONTAINER MANAGEMENT:"
echo "--------------------"
echo "Start stack:"
echo "  cd $STACK_DIR && docker-compose up -d"
echo ""
echo "Stop stack:"
echo "  cd $STACK_DIR && docker-compose down"
echo ""
echo "Restart Moodle container:"
echo "  docker-compose -f $STACK_DIR/docker-compose.yml restart moodle"
echo ""
echo "Rebuild containers:"
echo "  cd $STACK_DIR && docker-compose up --build -d"
echo ""
echo "Remove containers and volumes (WARNING: deletes data!):"
echo "  cd $STACK_DIR && docker-compose down -v"
echo ""

# ==================== TROUBLESHOOTING ====================
echo "TROUBLESHOOTING:"
echo "---------------"
echo "Check if Moodle is responsive:"
echo "  curl -f http://localhost:8080/index.php && echo 'OK' || echo 'FAILED'"
echo ""
echo "Check PHP-FPM status:"
echo "  docker exec moodle supervisorctl status php-fpm"
echo ""
echo "Check Nginx status:"
echo "  docker exec moodle supervisorctl status nginx"
echo ""
echo "View full Moodle error log:"
echo "  docker exec moodle tail -n 100 /var/log/php-fpm.log"
echo ""
echo "Restart PHP-FPM:"
echo "  docker exec moodle supervisorctl restart php-fpm"
echo ""
echo "Restart Nginx:"
echo "  docker exec moodle supervisorctl restart nginx"
echo ""

# ==================== PERFORMANCE ====================
echo "PERFORMANCE:"
echo "-----------"
echo "Check memory usage:"
echo "  docker stats moodle"
echo ""
echo "Database vacuum and analyze:"
echo "  docker exec moodle-db psql -U moodle -d moodle -c 'VACUUM ANALYZE;'"
echo ""

# ==================== SECURITY ====================
echo "SECURITY:"
echo "--------"
echo "Update admin password (from Moodle web interface):"
echo "  1. Log in as admin"
echo "  2. Site Administration > Users > Browse list of users"
echo "  3. Edit admin user > Change password"
echo ""
echo "Generate new config salt:"
echo "  openssl rand -base64 32"
echo ""

# ==================== ACCESS ====================
echo "ACCESS:"
echo "------"
echo "Moodle URL: https://moodle-stg.ligjamaica.com (or configured URL)"
echo "Local access: http://localhost:8080"
echo "Database: moodle-db:5432"
echo ""

# ==================== USEFUL COMMANDS ====================
echo "USEFUL COMMANDS:"
echo "---------------"
echo "List all containers:"
echo "  docker ps -a"
echo ""
echo "List all volumes:"
echo "  docker volume ls"
echo ""
echo "Inspect Moodle container:"
echo "  docker inspect moodle | less"
echo ""
echo "Execute command in Moodle container:"
echo "  docker exec -it moodle bash"
echo ""
echo "Copy files from container:"
echo "  docker cp moodle:/app/config.php ./config.php"
echo ""
echo "Copy files to container:"
echo "  docker cp ./config.php moodle:/app/config.php"
echo ""

# ==================== UPDATE ====================
echo "UPDATE:"
echo "------"
echo "Update Moodle from repository:"
echo "  cd /etc/komodo/repos/moodle"
echo "  git pull origin main"
echo "  cd $STACK_DIR"
echo "  docker-compose up --build -d"
echo ""

# ==================== UNINSTALL ====================
echo "UNINSTALL:"
echo "---------"
echo "Remove stack (preserves data):"
echo "  cd $STACK_DIR && docker-compose down"
echo ""
echo "Remove stack and all data (WARNING: PERMANENT!):"
echo "  cd $STACK_DIR && docker-compose down -v"
echo "  rm -rf $STACK_DIR"
echo ""
